language: r
sudo: require
cache: packages
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
r_github_packages:
- leeper/MTurkR
- eddelbuettel/drat
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
  - secure: Kg4ZQvRHolP5lKs8HTwU7Tq8GoDFsL67HWwcpRSeIEJRxPiEo7Fz2OwsdRfXcG69Zl2PP6089HwAylrxoe4YiZUIFJPER4gJnkRz93Iq/K4QinBmtMzIDwIOds4y0pq0VFZJIQMNrgMtaIZFZyylYxfZbrSK25ynCGG/oFvaFGU=
  - secure: IjOpSS6gkpVW7j9uSSjlCRhWR925LA1E8J8GaDeY6sYoxhtMBOS1UNLcvpIYVNcv0ahJm2WoqG8JzYjQ2JK9eou/4BZ4lnR5qsYlQi+8s86ZQtEq6AWl5+2tieGaVYh0nPqgfTxl0rLrhR8NeliRy9lSyrnK1gSnJ4jKGJ1N/lOZt5tN60mm3+J1B+BMi6mUUCcyXhCRWMbirEHagmS32NpfWb4gGF2eo3hpWjghudWy3uz8f1pVRax+O6b2IQ23kLKI5myCtu8r0ElGue0B23/Cuj8jun0vPX6Ya4DwJF1pppCKbIGDvj0qva44FRg51fYyuXsSTnzTRlTWtPzxOQuDqJmaPg2zlKbreNl4xfwsN/qLNYDSbpMzd2H1Wc5vXFGVbOM3xCbxElbaMQj9bVKgUDndnOahvZG0YNiPrPSmMVcKZCyYH65eoStyDpiL+CGmacNKza+hUKwvPUm91yxdYV/lF9IvhMVIQWaTiDjpB6cTKZ1UFmVaEtgTlk954O31xGnUfg5181MOYj9roUjXbnhdxcdYZn6zQgNvZRh9JscWJYmtggBn553B9peNawWbxEfdUjqDoXyhcOjyF0tcx4uwXzioithyiQPVoQ4E4MMK9bhZ+tKrRU76FCEwUWul/2UrODcaSxp5MmpUY1Z8WWnWC1SkiQVNtD3wYF4=
